---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: scalabilitya-user
rules:
- apiGroups: ["apps"]
  resources:
  - deployments
  - pods
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scalabilitya-user
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: scalabilitya-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scalabilitya-user
subjects:
- kind: ServiceAccount
  name: scalabilitya-user
  namespace: default