gauge-types:
  KubowGaugeT:
    commands:
      setServiceProperty: ServiceT.setServiceProperty (Object)
      setDeploymentInfo: DeploymentT.setDeploymentInfo (Object)
      setDeploymentProperty: DeploymentT.setDeploymentProperty (Object)
    setupParams:
      targetIP:
        type: String
        default: "127.0.0.1"
      propertyPath:
        type: String
        default: ""
      propertyName:
        type: String
        default: ""
      beaconPeriod:
        type: long
        default: 3000
      javaClass:
        type: String
        default: "br.unifor.kubow.gauges.KubowGauge"
    configParams:
      targetProbeType:
        type: String
        default: ~
    comment: ""
gauge-instances:

  SloGauge:
    type: KubowGaugeT
    model: "KubeZnnSystem:Acme"
    commands:
      "setServiceProperty()": "kubeZnnS.setServiceProperty($<jsonValue>,<slo>)"
    setupValues:
      targetIP: "127.0.0.1"
    configValues:
      targetProbeType: default-kube-znn-slo@*

  TrafficGauge:
    type: KubowGaugeT
    model: "KubeZnnSystem:Acme"
    commands:
      "setServiceProperty()": "kubeZnnS.setServiceProperty($<jsonValue>,<traffic>)"
    setupValues:
      targetIP: "127.0.0.1"
    configValues:
      targetProbeType: default-kube-znn-traffic@*
  
  ReplicasHighaGauge:
    type: KubowGaugeT
    model: "KubeZnnSystem:Acme"
    commands:
      "setDeploymentProperty()": "kubeZnnD.setDeploymentProperty($<jsonValue>,<replicasHigha>)"
    setupValues:
      targetIP: "127.0.0.1"
    configValues:
      targetProbeType: default-kube-znn-replicasHigha@*
    
  ReplicasLowaGauge:
    type: KubowGaugeT
    model: "KubeZnnSystem:Acme"
    commands:
      "setDeploymentProperty()": "kubeZnnD.setDeploymentProperty($<jsonValue>,<replicasLowa>)"
    setupValues:
      targetIP: "127.0.0.1"
    configValues:
      targetProbeType: default-kube-znn-replicasLowa@*

  ReplicasTextaGauge:
    type: KubowGaugeT
    model: "KubeZnnSystem:Acme"
    commands:
      "setDeploymentProperty()": "kubeZnnD.setDeploymentProperty($<jsonValue>,<replicasTexta>)"
    setupValues:
      targetIP: "127.0.0.1"
    configValues:
      targetProbeType: default-kube-znn-replicasTexta@*

  ReplicasHighbGauge:
    type: KubowGaugeT
    model: "KubeZnnSystem:Acme"
    commands:
      "setDeploymentProperty()": "kubeZnnD.setDeploymentProperty($<jsonValue>,<replicasHighb>)"
    setupValues:
      targetIP: "127.0.0.1"
    configValues:
      targetProbeType: default-kube-znn-replicasHighb@*
    
  ReplicasLowbGauge:
    type: KubowGaugeT
    model: "KubeZnnSystem:Acme"
    commands:
      "setDeploymentProperty()": "kubeZnnD.setDeploymentProperty($<jsonValue>,<replicasLowb>)"
    setupValues:
      targetIP: "127.0.0.1"
    configValues:
      targetProbeType: default-kube-znn-replicasLowb@*

  ReplicasTextbGauge:
    type: KubowGaugeT
    model: "KubeZnnSystem:Acme"
    commands:
      "setDeploymentProperty()": "kubeZnnD.setDeploymentProperty($<jsonValue>,<replicasTextb>)"
    setupValues:
      targetIP: "127.0.0.1"
    configValues:
      targetProbeType: default-kube-znn-replicasTextb@*

  StabilityGauge:
    type: KubowGaugeT
    model: "KubeZnnSystem:Acme"
    commands:
      "setDeploymentProperty()": "kubeZnnD.setDeploymentProperty($<jsonValue>,<stability>)"
    setupValues:
      targetIP: "127.0.0.1"
    configValues:
      targetProbeType: default-kube-znn-stability@*

  KubeZnnInfoGauge:
    type: KubowGaugeT
    model: "KubeZnnSystem:Acme"
    commands:
      "setDeploymentInfo()": kubeZnnD.setDeploymentInfo($<jsonValue>)
    setupValues:
      targetIP: "127.0.0.1"
    configValues:
      targetProbeType: deployments.default.kube-znn.probe@*